name: 🏷️ Versioning

on:
  push:
    branches: [development]

jobs:
  versioning:
    runs-on: ubuntu-24.04
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Fetch all history
          token: ${{ secrets.PAT }}

      - name: 🔑 Git credentials
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: ⬇️ Download cocogitto
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cocogitto
          version: "7.0.0"

      - name: 🏷️ Versioning
        run: cog bump --auto --skip-ci

      - name: 🚀 Push
        run: git push --follow-tags